"""Add recurring_expense_id foreign key on transactions

Revision ID: 2026_03_11_1300
Revises: 2026_03_08_1500
Create Date: 2026-03-11 13:00:00.000000+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = "2026_03_11_1300"
down_revision: Union[str, None] = "2026_03_08_1500"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Column already created in initial migration, no action needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Column will be dropped by initial migration downgrade
    pass
    # ### end Alembic commands ###
