"""Add bank_accounts table for storing real balances

Revision ID: 2026_03_06_1630
Revises: ed14aa0d33e2
Create Date: 2026-03-06 16:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '2026_03_06_1630'
down_revision: Union[str, None] = 'ed14aa0d33e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table already created in initial migration, no action needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table will be dropped by initial migration downgrade
    pass
    # ### end Alembic commands ###
