"""initial migration

Revision ID: 1000_initial
Revises: 
Create Date: 2026-03-14 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1000_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('oauth_id', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('profile_picture', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('encryption_key_salt', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('oauth_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    
    # Create bank_credentials table
    op.create_table('bank_credentials',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('bank_name', sa.String(), nullable=False),
        sa.Column('bank_label', sa.String(), nullable=True),
        sa.Column('bank_website', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('encrypted_login', sa.String(), nullable=False),
        sa.Column('encrypted_password', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_sync_at', sa.DateTime(), nullable=True),
        sa.Column('sync_status', sa.String(), nullable=True),
        sa.Column('sync_error_message', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_credentials_user_id'), 'bank_credentials', ['user_id'], unique=False)
    
    # Create bank_accounts table
    op.create_table('bank_accounts',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('account_label', sa.String(), nullable=False),
        sa.Column('account_type', sa.String(), nullable=True),
        sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('credential_id', UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_sync_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['credential_id'], ['bank_credentials.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_credential_id'), 'bank_accounts', ['credential_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    
    # Create recurring_expenses table
    op.create_table('recurring_expenses',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('pattern_name', sa.String(), nullable=False),
        sa.Column('pattern', sa.Enum('WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'UNKNOWN', name='recurrencepattern'), nullable=True),
        sa.Column('average_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('amount_variation_pct', sa.Float(), nullable=True),
        sa.Column('frequency_days', sa.Integer(), nullable=True),
        sa.Column('day_of_month', sa.Integer(), nullable=True),
        sa.Column('day_of_week', sa.Integer(), nullable=True),
        sa.Column('next_expected_date', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('matching_label_pattern', sa.String(), nullable=False),
        sa.Column('matched_transaction_count', sa.Integer(), nullable=False),
        sa.Column('first_seen_date', sa.Date(), nullable=False),
        sa.Column('last_seen_date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_user_id'), 'recurring_expenses', ['user_id'], unique=False)
    
    # Create transactions table
    op.create_table('transactions',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('raw_label', sa.String(), nullable=False),
        sa.Column('cleaned_label', sa.String(), nullable=True),
        sa.Column('category', sa.Enum('HOUSING', 'TRANSPORTATION', 'FOOD', 'UTILITIES', 'HEALTHCARE', 'ENTERTAINMENT', 'GROCERIES', 'DINING', 'SHOPPING', 'HOME_IMPROVEMENT', 'SUBSCRIPTIONS', 'INCOME', 'INSURANCE', 'EDUCATION', 'TRAVEL', 'OTHER', name='transactioncategory'), nullable=True),
        sa.Column('is_expense', sa.Boolean(), nullable=True),
        sa.Column('is_recurring', sa.Boolean(), nullable=True),
        sa.Column('merchant_name', sa.String(), nullable=True),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('credential_id', UUID(as_uuid=True), nullable=False),
        sa.Column('recurring_expense_id', UUID(as_uuid=True), nullable=True),
        sa.Column('transaction_key', sa.String(), nullable=False),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('original_currency', sa.String(), nullable=True),
        sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('ai_confidence', sa.Float(), nullable=True),
        sa.Column('ai_category_reasoning', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('enriched_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['credential_id'], ['bank_credentials.id'], ),
        sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_credential_id'), 'transactions', ['credential_id'], unique=False)
    op.create_index(op.f('ix_transactions_recurring_expense_id'), 'transactions', ['recurring_expense_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_key'), 'transactions', ['transaction_key'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    
    # Create enrichment_rules table (depends on users and transactions)
    op.create_table('enrichment_rules',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('label_fingerprint', sa.String(), nullable=False),
        sa.Column('merchant_name', sa.String(), nullable=True),
        sa.Column('cleaned_label', sa.String(), nullable=False),
        sa.Column('category', sa.Enum('HOUSING', 'TRANSPORTATION', 'FOOD', 'UTILITIES', 'HEALTHCARE', 'ENTERTAINMENT', 'GROCERIES', 'DINING', 'SHOPPING', 'HOME_IMPROVEMENT', 'SUBSCRIPTIONS', 'INCOME', 'INSURANCE', 'EDUCATION', 'TRAVEL', 'OTHER', name='transactioncategory'), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('learned_from_transaction_id', UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['learned_from_transaction_id'], ['transactions.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_rules_label_fingerprint'), 'enrichment_rules', ['label_fingerprint'], unique=False)
    op.create_index(op.f('ix_enrichment_rules_user_id'), 'enrichment_rules', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recurring_expense_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_credential_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_enrichment_rules_user_id'), table_name='enrichment_rules')
    op.drop_index(op.f('ix_enrichment_rules_label_fingerprint'), table_name='enrichment_rules')
    op.drop_table('enrichment_rules')
    op.drop_index(op.f('ix_recurring_expenses_user_id'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_credential_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_bank_credentials_user_id'), table_name='bank_credentials')
    op.drop_table('bank_credentials')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
