"""Add bank_accounts table for storing real balances

Revision ID: 2026_03_06_1630
Revises: ed14aa0d33e2
Create Date: 2026-03-06 16:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '2026_03_06_1630'
down_revision: Union[str, None] = 'ed14aa0d33e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists before creating
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'bank_accounts' not in inspector.get_table_names():
        op.create_table('bank_accounts',
            sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('account_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='unknown'),
            sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
            sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='EUR'),
            sa.Column('id', UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', UUID(as_uuid=True), nullable=False),
            sa.Column('credential_id', UUID(as_uuid=True), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('last_sync_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['credential_id'], ['bank_credentials.id'], ),
            sa.Index('ix_bank_accounts_user_id', 'user_id'),
            sa.Index('ix_bank_accounts_credential_id', 'credential_id'),
            sa.Index('ix_bank_accounts_account_id', 'account_id'),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
